In [5]:
import os
import pandas as pd
import numpy as np
import statsmodels.api as sm
import warnings
from statsmodels.tsa.arima.model import ARIMA
from scipy.spatial.distance import pdist, squareform
from sklearn.cluster import AgglomerativeClustering
from joblib import Parallel, delayed
from scipy.stats import norm
import time
from itertools import product
from tqdm import tqdm

# Function to determine the best ARIMA order and keep a rolling model copy
# Intermediate function
def best_arima(series, max_p=5, max_q=5, max_d=3):
    """
    Automatically selects the best ARIMA hyperparameters (p, d, q) based on AIC and fits the model.
    Returns both the best order and the fitted model (model_fit).
    If no valid model is found, returns (None, None).
    """
    def _try_arima(p, d, q, series):
        try:
            # Suppress warnings during model fitting
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                model = ARIMA(series, order=(p, d, q))
                model_fit = model.fit()
            return (p, d, q), model_fit, model_fit.aic
        except:
            return None, None, float('inf')
    
    # Parallel processing of ARIMA models
    param_combinations = list(product(range(1,max_p), range(1, max_d), range(1, max_q)))
    results = Parallel(n_jobs=-1)(
        delayed(_try_arima)(p, d, q, series) 
        for p, d, q in param_combinations
    )
    
    # Find the best model
    best_aic = float('inf')
    best_order = None
    best_model_fit = None
    
    for order, model_fit, aic in results:
        if aic < best_aic and order is not None:
            best_aic = aic
            best_order = order
            best_model_fit = model_fit
    
    if best_order is None:
        print("Warning: No valid ARIMA model found for the series")
        
    return best_order, best_model_fit



def Forecast(series, train_l=400, h_lst=[1, 3, 6, 12]):
    """
    Forecasts using ARIMA with a rolling window.
    - series: the time series data
    - train_l: length of the training set (400).
    - out_l: length of the out-of-sample data (R).
    - h: forecast horizon.
    - max_p, max_q: maximum order for ARIMA parameters (p, q). 
    """

    h_max = max(h_lst)
    forecasts = []
    residuals = []
    out_l = len(series) - train_l
    print(series.shape)  
    print(out_l)

    for i in range(out_l - 1):  # Loop over each time step in the out-of-sample period
        # Define the training window
        train_data = series[i:i+train_l]
        
        # Fit ARIMA model on the training window
        best_order, best_model_fit = best_arima(train_data)  # ARIMA(p, d, q)
        location = np.array(h_lst) - 1
        forecast = best_model_fit.forecast(steps=h_max)[location]
        print(forecast)
        print()
        forecasts.append(forecast)
        
    return forecasts

# colloect forecasts and residuals for all series for some horizon h

def collect_forecasts(S, Basey, train_l, h_lst=[1,3,6,12]):
    
    '''
    # Collect forecasts and residuals for all series for horizon h
    # Parameters:
    # S: summation matrix, (num_of_series, num_of_base_stock)
    # Basey: compositions of index, (num_of_dates, num_of_base_stock) 
    # train_l: length of training window, default=400
    # out_l: length of out-of-sample period
    # h: forecast horizon    
    '''

    Y_mat = S @ np.array(Basey).T # (num of series, num of dates)
    forecasts_all = []
    
    for i in tqdm(range(Y_mat.shape[0]), desc="Processing series"):
        series = Y_mat[i]
        forecasts = Forecast(series, train_l, h_lst)
        forecasts_all.append(forecasts)
    
    # Save forecasts to a CSV file
    forecasts_df = pd.DataFrame(forecasts_all)
    forecasts_df.to_csv('data/forecasts.csv', index=False)
    return np.array(forecasts_all)

def G_mat(S, forecasts_all, residuals_all):

    """
    Perform MinT reconciliation using the summation matrix S and the covariance matrix W_h.
    residuals_all: matrix of residuals, (num of series, out_l)
    S: summation matrix, (n_a + num of stock, num of stock)
    forecasts_all: matrix of forecasts, (num of series, out_l)
    """
    S = np.array(S)
    row, column = forecasts_all.shape[0], forecasts_all.shape[1] #

    # calculate covariance matrix W_h
    W_h = np.cov(residuals_all) # (num of series, num of series)
    print(W_h.shape)

    # check if the covariance matrix is correct
    if W_h.shape[0] != row:
        print("Fail to calculte the covariance matrix")
        return None
    
    # calculate MinT reconciliation matrix G_h, (num of base stock, num of series)
    W_inverse = np.linalg.inv(W_h)

    # Print shapes for debugging
    print("S.T shape:", S.T.shape)
    print("W_inverse shape:", W_inverse.shape)
    print("S shape:", S.shape)

    # Check the data types of the matrices
    print("Data type of S:", type(S))
    print("Data type of W_inverse:", type(W_inverse))

    

    try:
        G_h = np.linalg.inv(S.T @ W_inverse @ S) @ (S.T @ W_inverse)
    except ValueError as e:
        print("Matrix alignment error:", e)
        return None

    G_h = np.linalg.inv(S.T @ W_inverse @ S) @ S.T @ W_inverse

    return G_h

In [6]:
# Load data
Basey = pd.read_excel(os.path.join("data", "DataP0.xlsx"), index_col='Dates0')
# DJIA_dat = pd.read_excel(os.path.join("data", "DJIA - composition at 2020.xlsx"))   
h_lst = [1,3,6,12]
S = np.array(pd.concat([pd.DataFrame(np.ones((1, Basey.shape[1]))/0.15), pd.DataFrame(np.eye(Basey.shape[1]))], axis=0)) # (Nnum of base stock+1,num of base stock)

In [7]:
forecasts_all = collect_forecasts(S, Basey, 400, h_lst) #(num_series, num_forecasts, num_horizons)

Processing series:   0%|          | 0/31 [00:00<?, ?it/s]

(524,)
124
[232571.67774421 232569.28750595 232585.37456067 232563.74241453]

[233054.05734883 233000.08689227 233080.79588331 232996.22821974]

[231453.46022424 231624.27265339 232090.40551896 232717.15269404]

[230242.07652807 230414.54328672 230828.07677315 231327.48681735]

[230723.22913084 230650.07431039 230859.93727636 230685.98352477]

[231683.53365271 231726.18903745 231802.60638703 231732.00888899]

[228916.31986877 228900.70778133 228897.54941719 228897.29063832]

[228349.19342609 228429.26962863 228347.73666276 228467.86974016]

[230665.99580757 230665.58497926 230665.58317525 230665.58317578]

[230007.29167494 230000.06702616 229951.82628571 229996.19456964]

[229695.17076836 229669.38106048 229474.07020143 229658.33584662]

[233050.29372625 233010.83900755 233099.80394765 233067.88364417]

[234673.48554293 234921.79544137 235393.72716993 236107.70323006]

[232154.83143594 232162.80671266 232171.03616833 232169.32376635]

[225839.95721321 225848.01821312 225859.90673347 22

Processing series:   3%|▎         | 1/31 [10:03<5:01:42, 603.42s/it]

[196348.00084626 196350.26427914 196350.41859185 196350.41619614]

(524,)
124
[1157.31848681 1161.98004918 1165.64820134 1167.73622277]

[1187.82426991 1189.44475813 1191.07532698 1195.9435521 ]

[1165.76724305 1166.92839885 1170.42306709 1175.22713103]

[1143.141092   1144.87814867 1147.48373645 1152.69491201]

[1145.34895081 1147.3634195  1150.38479568 1156.42754795]

[1131.28576138 1133.06965781 1135.75555109 1141.12734371]

[-31448.96394072 -31610.49309163 -31923.74291981 -32407.01313969]

[1115.74464821 1117.64329508 1120.48294005 1126.16222487]

[1134.31690703 1135.67831881 1138.57903872 1144.3226313 ]

[1099.0155328  1100.68755129 1103.2122383  1108.26161927]

[1099.86433189 1100.15154669 1102.98889797 1108.67883425]

[1114.79580172 1115.86811329 1118.87801444 1124.79339461]

[1106.59065692 1113.77231303 1107.69187266 1113.10709605]

[1108.02583884 1109.07610737 1111.90107286 1117.68595301]

[1076.97258221 1078.26713628 1080.97020466 1086.25380135]

[1081.61678327 1085.38799291 

Processing series:   6%|▋         | 2/31 [23:21<5:47:01, 717.99s/it]

[1010.42096074 1013.21264596 1013.49599811 1015.40470088]

(524,)
124
[1594.63421639 1594.87338603 1594.86951867 1596.4585489 ]

[1609.16861623 1609.65250611 1606.95912192 1609.62551813]

[1603.42048504 1604.604044   1604.40291736 1605.49722743]

[1643.15621418 1642.42123301 1642.6507788  1642.24147043]

[1649.08681367 1650.07417567 1648.81681622 1650.26962279]

[1651.74878201 1653.53280515 1653.68742956 1656.39872864]

[1649.52888002 1647.95288566 1650.30110696 1653.68231552]

[1640.36208432 1642.54788663 1642.67703695 1641.91483002]

[1662.68191367 1662.9085685  1663.70041913 1668.46729517]

[1671.5773319  1670.00774654 1672.33163126 1672.698045  ]

[1649.40232221 1652.84055602 1651.87129301 1652.8956386 ]

[1665.40167847 1663.3945716  1665.63953626 1669.75523081]

[1677.68035214 1678.46731216 1679.42557137 1678.92531666]

[1673.29788939 1675.10172583 1674.03570723 1673.79435615]

[1642.26693174 1648.42795589 1646.63248291 1645.40535289]

[1652.38362325 1654.98851158 1654.92509342 16

Processing series:  10%|▉         | 3/31 [37:03<5:57:16, 765.60s/it]

[1506.226723   1508.5202881  1508.23049206 1507.39630283]

(524,)
124
[1233.60334028 1228.8282444  1233.14904938 1230.69028834]

[1235.21784892 1233.36527021 1240.2830855  1234.34161997]

[1221.04209633 1223.31033333 1227.74532995 1223.12983658]

[1213.13314536 1216.42663948 1217.3834089  1215.56279489]

[1207.99966178 1210.03569673 1209.72254656 1209.3998826 ]

[1216.95267382 1217.52727377 1216.56441048 1217.03420695]

[1174.46189858 1171.9036549  1165.10883739 1172.05613393]

[1160.95254935 1154.95764669 1149.82083183 1156.29879835]

[1187.05106606 1179.29191675 1184.85899805 1181.703038  ]

[1193.17739734 1191.48358119 1200.53612985 1192.52728758]

[1219.3003276  1224.17895958 1235.55107186 1223.9466887 ]

[1238.33635295 1248.30759157 1254.3039691  1245.05013767]

[ 2770.39589063  6772.41801039 11441.36752872 11975.44612988]

[1234.30328969 1242.2394173  1229.86640603 1238.73016676]

[1201.86045158 1197.97160911 1204.22963432 1202.91401644]

[1223.49955971 1211.54011997 1210.9240147

Processing series:  13%|█▎        | 4/31 [49:49<5:44:31, 765.60s/it]

[908.46929628 914.51540262 913.49996838 913.75746418]

(524,)
124
[1275.80644623 1275.44401049 1278.45494098 1273.28002092]

[1282.48717032 1269.96630146 1269.46396816 1265.04874461]

[1217.23149136 1212.10873298 1213.20645403 1211.56002131]

[1188.76767599 1182.95069024 1189.11054228 1187.608856  ]

[1183.72240328 1181.11397575 1186.43667111 1185.89122764]

[1165.59427387 1166.98476247 1168.19254845 1168.74455725]

[1166.78771566 1170.11607918 1167.85854196 1168.8303732 ]

[1176.51776002 1179.07653161 1176.00718446 1176.66866271]

[1220.50631476 1221.51308731 1221.8505581  1222.17712289]

[1213.13477394 1214.72713161 1212.91938197 1213.34853882]

[1198.33902146 1199.65342207 1198.68206333 1199.06097592]

[1239.45175171 1238.69951891 1242.19595523 1242.15025009]

[1222.54293647 1223.32722881 1223.37056937 1223.64808898]

[1207.27678305 1208.818164   1206.07152894 1206.41011235]

[1181.13164949 1180.41604331 1176.82715796 1176.35291299]

[1172.76638935 1164.73138045 1170.02313538 1167.8

Processing series:  16%|█▌        | 5/31 [59:28<5:02:39, 698.43s/it]

[846.1535456  843.20225408 838.79036704 829.96849003]

(524,)
124
[1449.38715988 1452.10985637 1456.08662849 1463.83271591]

[1455.22665717 1458.43484669 1462.00991315 1469.33178952]

[1424.62873944 1427.48778789 1431.14104587 1438.33949964]

[1425.40405463 1428.05061003 1431.54597578 1438.66891088]

[1424.67200061 1426.26512313 1429.97490866 1437.34920939]

[1430.83127215 1433.40314778 1436.79432215 1443.56398149]

[1424.30837284 1426.99522919 1430.44548446 1437.36358838]

[1429.64042863 1431.18419498 1434.61634815 1441.53399795]

[1439.78341409 1441.68501587 1445.26045848 1452.30945924]

[1504.79449616 1505.24012657 1509.68622799 1518.6971547 ]

[1516.64121367 1519.36217977 1523.68495761 1531.98514616]

[1529.80416555 1533.5144694  1537.38371315 1545.35434541]

[1541.8345345  1543.26868067 1545.40339315 1543.76650262]

[1531.56300111 1536.9153049  1541.29056068 1549.6380147 ]

[1426.00752368 1434.57177269 1437.13481049 1442.66621014]

[1441.49248057 1438.8094203  1443.14530567 1452.3

Processing series:  19%|█▉        | 6/31 [1:09:22<4:36:11, 662.87s/it]

[1078.40398655 1081.59228169 1075.51371063 1067.2074673 ]

(524,)
124
[1413.41303064 1412.43691899 1407.39735432 1399.78880277]

[1458.73779819 1454.73673375 1454.34275909 1449.60973418]

[1407.4293873  1405.78136911 1402.9778249  1395.52539334]

[1331.25805243 1331.51584244 1327.45285172 1327.39166867]

[1335.27990086 1333.84433642 1330.58388866 1326.69664646]

[1311.0939802  1309.44921408 1308.73996696 1303.1294133 ]

[1304.16734336 1302.31831516 1298.11055294 1293.12367307]

[1295.85727258 1294.35258574 1293.56373236 1288.48963113]

[1300.64552498 1301.72530471 1295.10664824 1292.88159388]

[1257.67628426 1255.78202768 1255.81666518 1249.07510189]

[1249.05084989 1246.75089638 1240.88826551 1234.8916643 ]

[1273.10104082 1271.41775491 1270.2829922  1264.71826153]

[1241.11407906 1239.20603999 1235.97489081 1230.3922527 ]

[1177.20839633 1175.00669133 1173.93901617 1166.48799989]

[1143.02474475 1140.35771391 1135.32883855 1127.72317445]

[1155.87743789 1157.42563953 1151.07666164 11

Processing series:  23%|██▎       | 7/31 [1:20:47<4:28:04, 670.18s/it]

[987.37993828 988.21291671 982.86343721 974.56498415]

(524,)
124
[362.20077827 362.1936419  362.49538185 362.15101564]

[363.6691353  362.9676001  363.1232876  363.55842732]

[360.25375224 362.8976814  365.89571451 369.54771987]

[357.96982328 358.77892752 359.34785785 360.10203455]

[356.73047992 357.81285518 358.15995851 361.14722408]

[356.98137193 356.91220157 358.65305006 358.63847449]

[345.90119785 347.2788668  347.41939943 347.96273281]

[340.3885968  341.49375611 342.97530124 343.62335908]

[343.41251346 343.78376284 343.779887   345.35240282]

[333.92259597 334.91299588 336.28227397 336.98283551]

[336.6129458  337.03564389 337.24262736 338.39434509]

[338.59871204 338.83014716 339.480945   341.52879588]

[349.04262583 347.85585612 349.13276067 349.61712249]

[343.17425902 344.72877502 344.71465048 347.48331261]

[336.70585478 337.91563411 339.46772257 339.56198018]

[341.73491456 342.27302761 341.98414106 344.5610157 ]

[331.76104419 332.93557231 334.47783738 335.426363  ]


Processing series:  26%|██▌       | 8/31 [1:32:16<4:19:09, 676.06s/it]

[267.10777631 266.01781635 264.40919024 261.18856502]

(524,)
124
[1068.8272326  1072.92137345 1079.46429317 1085.89252833]

[1087.92661381 1088.77789955 1093.55406926 1101.66845728]

[1063.59778405 1068.85240251 1070.05387083 1081.6588088 ]

[1086.50694506 1087.0544725  1096.25287701 1100.24509211]

[1096.44848418 1101.77965612 1100.72028636 1115.61165708]

[1115.04137529 1116.63455544 1127.27437269 1130.93426373]

[1088.65832357 1092.03996236 1091.81525608 1105.51211614]

[0. 0. 0. 0.]

[1136.21474653 1138.04983094 1142.56836063 1152.67731683]

[1118.8100829  1124.06563017 1127.28413186 1139.13459953]

[1146.71388696 1148.02268526 1156.5835956  1162.89553954]

[1125.80194869 1130.11851148 1131.85629271 1144.6885099 ]

[1131.55416082 1133.94476895 1142.0520445  1148.72807223]

[1082.4015374  1084.58671859 1086.71992744 1097.5592997 ]

[1047.04804124 1051.05756895 1056.36342708 1064.87594561]

[1038.12166659 1038.95633563 1045.19063799 1051.65759885]

[1021.54605018 1026.70431679 1027.

Processing series:  29%|██▉       | 9/31 [1:43:46<4:09:32, 680.55s/it]

[933.2859284  933.46506836 925.88501725 938.38458882]

(524,)
124
[913.59716024 914.58642546 914.05943727 914.89198916]

[926.92551749 923.91736816 924.85051582 925.50919494]

[902.99443919 904.58022088 904.20054409 902.80708788]

[883.45937732 888.57362645 885.79018647 886.3477565 ]

[877.55155736 878.84615697 878.33734923 877.88556554]

[879.37821085 875.0268662  871.38656899 864.16270182]

[869.44562072 867.32179357 863.10902925 853.69273359]

[874.23597864 873.50047564 873.84221206 873.50607283]

[880.64906333 880.87317224 880.35874295 880.48385195]

[870.67461389 870.55372901 871.14196742 871.1615048 ]

[851.28815421 854.52897716 853.97963631 852.5686036 ]

[882.93952204 879.16807268 880.59782391 882.74878403]

[833.44055723 832.54172051 832.98218919 830.09977759]

[804.62259431 809.07684026 799.97830539 786.85588792]

[793.08417027 784.61408981 778.83518597 766.5300122 ]

[796.22677619 793.80072615 786.79677918 771.84679645]

[764.34928527 763.03199483 752.94805126 735.55024403]


Processing series:  32%|███▏      | 10/31 [1:56:27<4:06:49, 705.22s/it]

[636.05642524 633.28297019 628.496128   620.18139116]

(524,)
124
[417.59158194 417.15370351 416.81705627 416.60365065]

[416.59714321 416.30585623 416.07651481 415.92533226]

[413.40605267 413.37870599 413.3558895  413.3393366 ]

[402.11404806 402.92190262 403.66921815 404.31341605]

[399.39871932 400.2554478  401.07915481 401.83697298]

[402.01722364 402.58683785 403.12018598 403.5894133 ]

[403.63240345 403.98711593 404.32024817 404.6148247 ]

[411.673899   411.29892041 410.95958738 410.67768793]

[417.24523347 416.44339241 415.71813341 415.11612737]

[425.55566542 424.21553111 422.97028565 421.88878011]

[428.06973463 426.69449024 425.42148429 424.32294278]

[11510140.6218673  11568562.90918447 -8545252.4807536  -8676237.71248907]

[438.70701547 437.04613523 435.46455473 434.03295348]

[451.22810856 449.14045021 447.21514072 445.56402001]

[445.06365721 443.60639429 442.28449898 441.18192123]

[442.53534476 441.48697839 440.54639052 439.776182  ]

[438.26568735 437.63567255 437.062

Processing series:  35%|███▌      | 11/31 [2:05:57<3:41:15, 663.76s/it]

[291.22464649 291.45890361 290.85067362 291.70325837]

(524,)
124
[2170.59893612 2168.11479509 2164.36321349 2156.85978794]

[2161.48411713 2164.58745825 2170.76297823 2183.19741101]

[2126.3398898  2122.45715475 2116.9722054  2106.00596386]

[2072.79949854 2067.20409936 2059.49691576 2044.09065962]

[2062.21376385 2056.6423682  2048.44392105 2032.04889858]

[2116.31400242 2113.0219475  2107.38961416 2096.11687357]

[2107.24631979 2103.1954821  2097.14860927 2085.05520015]

[2096.49608035 2083.26429484 2063.44543907 2023.88508535]

[2117.08475176 2113.587214   2108.11703764 2097.17412322]

[2108.14049116 2093.65598801 2072.71458574 2032.87152841]

[2173.61421275 2172.08393808 2168.98525825 2162.7782199 ]

[2212.7122282  2211.9085719  2210.06556423 2206.37125793]

[2242.16107997 2249.67392569 2256.38209714 2269.95549366]

[2195.57353119 2206.12964136 2213.5364142  2227.81436502]

[2084.20516608 2069.23597431 2046.88275423 2002.96713352]

[2108.86682731 2090.82798248 2064.98052042 2016.6

Processing series:  39%|███▊      | 12/31 [2:15:08<3:19:23, 629.64s/it]

[1938.96627483 1942.03785812 1941.34476945 1939.50475145]

(524,)
124
[1983.67829896 1972.5236709  1969.80778413 1987.41170903]

[2008.95553317 2015.72870041 2008.40695585 2012.71652448]

[2004.77226653 2009.63874388 2009.05618895 2005.5206362 ]

[1969.14010726 1963.60555271 1969.38553861 1970.08810072]

[1992.20350635 1985.34699398 1984.04396946 1994.92191232]

[2044.71670786 2061.30527161 2051.08790449 2052.10220897]

[2020.76764222 2025.32699789 2030.40147627 2017.99152829]

[2026.85740522 2010.8358188  2018.74437205 2021.77477326]

[2038.5485897  2035.73201736 2028.74447626 2042.12076565]

[1991.53777182 2006.8277067  2001.65813755 1994.90958689]

[1979.25948458 1978.65063256 1987.05615584 1973.92941673]

[2035.97414165 2022.79762564 2024.69375963 2034.44057671]

[2066.31119471 2075.30407535 2065.24006383 2071.55826351]

[2038.26102672 2050.16261837 2051.52100115 2038.13986263]

[1983.63078131 1966.69713803 1979.6113493  1975.75862002]

[2008.88057708 1994.6989688  1990.37846044 20

Processing series:  42%|████▏     | 13/31 [2:24:00<2:59:58, 599.92s/it]

[1788.8945092  1791.78833216 1792.30227077 1793.37772036]

(524,)
124
[1299.89084865 1291.27395161 1291.93615893 1290.54270092]

[1295.96268207 1296.46022559 1297.36776082 1300.74077277]

[1273.25155258 1271.07552406 1279.11687842 1279.09579941]

[1272.74552521 1279.8741238  1280.18896796 1281.99078175]

[1273.96047733 1284.11284573 1273.52564529 1275.56376518]

[1260.92188351 1265.51296007 1253.66802925 1253.68619674]

[1256.64130781 1254.65648964 1248.07437163 1246.48397139]

[1260.09669118 1249.60074675 1257.79775334 1255.36624343]

[1280.02701403 1270.81038253 1286.17554919 1285.38545759]

[1279.50199041 1282.26323003 1290.41826419 1291.42466684]

[1264.15983798 1275.70090346 1271.15127181 1272.86162696]

[1307.16681362 1315.56870462 1302.9063357  1304.64766601]

[1302.15990037 1302.55345311 1294.32039285 1293.99867738]

[1297.46589493 1289.04144483 1290.57857096 1288.7281471 ]

[1254.76969453 1247.53398203 1255.18480085 1253.08669221]

[1270.07122065 1262.67241869 1267.05345209 12

Processing series:  45%|████▌     | 14/31 [2:32:00<2:39:43, 563.75s/it]

[1133.70874567 1132.76499456 1131.17415362 1128.4986849 ]

(524,)
124
[849.68815616 846.14354731 845.92498382 846.24384513]

[845.26677579 847.05434929 846.54346116 845.28582048]

[837.13189282 839.10502463 839.72764697 840.45089389]

[844.86469356 841.40191449 841.3946644  842.05048625]

[834.62609437 835.78234128 835.23685801 834.0541407 ]

[829.05800979 831.50770185 832.03069688 832.48593893]

[824.95787593 822.01731485 822.25796182 823.25074862]

[819.17035603 818.91008595 818.3062667  817.29611688]

[817.96719984 820.96634714 821.22256356 821.09041696]

[825.49453931 823.40971702 823.75163057 824.74585175]

[821.12154071 820.18767802 819.68669464 818.9912978 ]

[837.40809935 840.10722685 839.8784856  838.86307645]

[899.2055767  898.89175737 906.49460603 896.11380452]

[905.1817388  907.71791135 906.52041442 890.94164817]

[899.45888205 899.95488559 900.48692265 901.02166627]

[904.70476326 904.71585841 904.78884627 904.77373942]

[885.15541759 885.22871356 885.69110635 885.593863

Processing series:  48%|████▊     | 15/31 [2:40:43<2:27:05, 551.58s/it]

[809.17731094 809.40180176 810.98649375 810.66765519]

(524,)
124
[315.77221223 318.42235794 315.28864038 315.51555093]

[321.81289123 321.48338351 321.17126468 321.0203266 ]

[314.61869078 315.85502558 315.93586064 315.4056773 ]

[311.98532039 311.74208073 312.10469263 312.58628734]

[312.31764947 311.17977982 311.13540126 311.62623155]

[308.04462536 308.06380035 308.06407273 308.06407318]

[305.08822359 305.10470397 305.10490529 305.10490556]

[304.53372337 304.53878477 304.53885412 304.53885423]

[306.89748354 307.4863581  307.07994327 306.37690701]

[299.22756075 297.70152721 298.99224321 298.91983433]

[305.18898321 305.16404593 305.16378549 305.16378521]

[314.53310152 315.32616124 316.33869703 318.9663994 ]

[314.50629902 314.96297604 315.59246346 316.281683  ]

[311.17966891 311.2061068  311.20685216 311.20685558]

[305.6762391  304.57818133 304.17914353 304.30598602]

[307.58067866 308.70261347 308.03509037 307.30033878]

[298.60973546 296.44634381 298.50668674 298.44721327]


Processing series:  52%|█████▏    | 16/31 [2:49:39<2:16:42, 546.82s/it]

[177.68247536 177.50849423 174.71308597 172.81865489]

(524,)
124
[1168.34320566 1169.85986323 1172.66400902 1174.77508618]

[1166.26412083 1165.34957752 1167.06881289 1169.01117432]

[1166.4557198  1167.02105126 1166.19827813 1165.57134551]

[1198.77518996 1203.72296156 1202.51595432 1206.9397299 ]

[1202.31631038 1199.28744455 1200.78767736 1204.91144632]

[1196.78159335 1195.58035442 1197.44142611 1201.18057982]

[1181.91983659 1181.48607168 1185.47768167 1189.00405576]

[1182.39461767 1185.42869047 1187.67643512 1191.27935326]

[1188.84908942 1188.91044591 1188.96856793 1188.98497508]

[1184.34895407 1183.6297933  1183.64754857 1183.69730277]

[1168.65197732 1168.15305704 1167.90887932 1167.85662917]

[1202.49861582 1205.53462662 1204.39389011 1212.08584235]

[1210.95527739 1210.71824507 1216.67903933 1216.49302335]

[1209.35762685 1209.35809515 1212.06961906 1216.84413636]

[1192.66105247 1193.67728239 1198.47169485 1200.30869394]

[1221.53663188 1225.98813182 1228.71452843 1233.3

Processing series:  55%|█████▍    | 17/31 [2:58:08<2:04:55, 535.41s/it]

[1099.91309809 1098.89950006 1102.20128936 1101.82205578]

(524,)
124
[877.92015445 864.86901636 854.03190798 855.30031023]

[878.93509195 867.83873875 853.87107521 848.61847149]

[869.404941   875.126405   877.03049382 879.30612429]

[857.21993159 845.09321397 837.90240619 855.34595734]

[856.03376034 845.01622165 839.02533528 854.11385153]

[871.1786931  874.08777428 873.41761434 871.47575865]

[867.97647767 870.27322865 869.09299107 865.23560668]

[864.69947172 859.61370095 858.20985004 856.31996261]

[827.92633716 830.1591607  837.52729745 867.54215756]

[824.21276471 827.56209704 840.03142873 874.81514781]

[845.10159517 840.14865003 839.50117578 839.30300578]

[858.30594977 857.79179379 856.72141425 855.28656673]

[858.59398829 862.590353   862.94280896 862.20302061]

[858.63776678 855.39506752 856.18449544 858.42895764]

[830.6566652  828.65747831 826.8015873  824.05127747]

[826.29510302 829.16271781 827.5494702  823.06532663]

[806.49662978 804.53750001 803.54885954 801.306343

Processing series:  58%|█████▊    | 18/31 [3:07:00<1:55:48, 534.49s/it]

[700.63691602 699.18538779 699.45729888 700.31905576]

(524,)
124
[411.50327815 413.31892    413.57190133 414.69833192]

[412.52299912 411.33764087 411.86330386 412.22015266]

[411.3338236  411.85214088 412.48578094 413.08572075]

[413.85521336 414.69054969 415.06958498 417.57874183]

[418.1416973  418.12435763 419.53183252 420.2818119 ]

[419.02737359 420.18490325 420.27851897 422.20559125]

[419.0213582  418.89108482 418.70493625 418.99721789]

[425.53917277 424.61799011 424.99239111 425.35510954]

[424.46077242 425.33629391 425.81933296 428.66867291]

[428.66194293 428.61176014 430.04808381 430.64339719]

[422.85072423 423.98761957 424.08902668 426.24316056]

[428.23714984 428.28856337 429.70711771 431.30680506]

[433.91784135 434.78140923 435.30389686 436.52865941]

[434.56082849 435.29036294 436.20185614 439.13394117]

[430.31942956 430.36472411 431.80425279 432.36202567]

[434.40760904 435.0995935  435.73477415 437.58354729]

[426.70333014 426.50027065 427.02864421 427.21538202]


Processing series:  61%|██████▏   | 19/31 [3:14:59<1:43:31, 517.59s/it]

[373.69627689 373.98143435 375.61635168 375.4936496 ]

(524,)
124
[1643.48799869 1646.05726943 1648.36100974 1652.91390102]

[1631.03180663 1630.13732159 1630.74040562 1634.40799945]

[1639.13161774 1641.27419321 1643.33393524 1647.79882954]

[1657.7856945  1662.92142874 1663.78015781 1669.50721919]

[1681.14437237 1685.13621403 1688.97132024 1693.51870315]

[1660.48251258 1659.84426089 1661.68824861 1665.7344996 ]

[1651.54226048 1650.86202826 1654.10581272 1657.46934997]

[1641.66935275 1642.31326893 1642.66504364 1647.08588375]

[1657.41335162 1659.87042335 1662.7307816  1666.33278419]

[1653.00274488 1654.23975859 1654.82288732 1658.81093174]

[1655.23418167 1655.83131393 1660.00058035 1662.87285455]

[1685.48376431 1692.32213612 1690.14516957 1695.50778024]

[1687.80008731 1689.74138447 1696.06204355 1699.43497388]

[1689.45683539 1690.27962666 1689.39729794 1694.4952602 ]

[1645.29551237 1641.24681532 1647.63619475 1650.04440488]

[1670.61947769 1673.8131388  1671.23041909 1677.2

Processing series:  65%|██████▍   | 20/31 [3:23:10<1:33:28, 509.89s/it]

[1574.5220288  1576.66019789 1578.81641666 1581.63242532]

(524,)
124
[979.05762517 979.14208727 976.68573664 978.57028031]

[976.99341911 975.85605666 974.45124391 975.86480663]

[972.74086525 969.8101685  968.6674299  969.61054824]

[980.59871253 977.97291397 980.15180263 978.32674679]

[978.05677583 976.86694835 980.39055268 977.38111288]

[977.56558816 978.35211302 981.84023622 978.77342409]

[980.44888282 982.27795467 983.64499817 982.54262539]

[971.78795254 975.86243561 974.31872475 975.78851837]

[973.50374147 975.34165541 971.03917478 974.30117591]

[964.21378931 964.76330607 960.65499495 964.35156327]

[955.8776739  952.61689758 944.00649866 938.99559151]

[979.42957663 974.19425013 975.2628566  974.25402779]

[980.57566915 976.15968674 982.1561968  977.27331175]

[989.4123663  986.4980025  983.53208802 977.44400492]

[971.72682405 973.13233874 974.44674448 965.03577375]

[971.8592495  969.34297615 965.76858598 958.54954383]

[942.49769643 942.40835958 937.56636892 928.432290

Processing series:  68%|██████▊   | 21/31 [3:30:59<1:22:54, 497.43s/it]

[756.72592498 765.0336268  779.88615374 820.07030776]

(524,)
124
[547.67871001 547.48011516 547.5876359  548.18451095]

[548.93735554 548.93472106 548.5143655  548.58057357]

[548.43579081 548.91938293 548.73041058 548.77852889]

[558.51283065 557.67520406 558.00135578 558.5692637 ]

[568.91847544 570.40382634 569.30026805 568.99445859]

[576.30448896 578.48677624 576.48540853 576.94254243]

[569.03569846 568.62603158 568.79636349 568.66854255]

[561.83467002 559.17816818 561.00051553 560.95066211]

[563.75377849 561.59684099 564.39503537 563.46651733]

[568.701348   570.16239557 569.87615531 569.29608431]

[564.47325853 567.45383507 564.27900877 564.97284871]

[563.98970342 564.98543631 563.42675923 564.38343443]

[568.62523359 566.39860665 568.16751522 568.00912203]

[564.88854133 562.78235745 565.03327904 564.52381384]

[554.28177398 553.58928796 554.54244204 554.08453586]

[560.11962828 560.22200499 560.19043691 560.39921469]

[554.80369737 554.52678325 554.64263222 554.40226537]


Processing series:  71%|███████   | 22/31 [3:39:16<1:14:35, 497.31s/it]

[573.32090523 573.19684523 572.59737595 572.73473514]

(524,)
124
[2049.67092159 2053.45645639 2057.70910569 2069.94065832]

[2096.04414006 2096.75681588 2103.49083021 2108.6402278 ]

[2063.71785845 2068.94951134 2070.68165696 2081.90107862]

[1991.60482067 1993.19114459 1999.18184036 2005.86814291]

[2000.01049538 2005.04421601 2007.77166838 2019.99443554]

[1974.57680168 1975.71599728 1982.6312345  1989.01216558]

[1902.90254519 1904.12916116 1908.63538837 1910.0756206 ]

[1864.67974872 1871.11317844 1871.15755938 1887.58038507]

[1914.49984934 1914.77225221 1922.13710132 1926.52708889]

[1858.99112279 1863.07336152 1863.82539167 1871.62743206]

[1859.73982393 1862.22636435 1867.35403845 1877.25285216]

[-6154.34548364 -6170.94359001 -6195.25203927 -6241.74135569]

[1898.53802836 1903.23713018 1905.77646893 1917.58119691]

[1868.77126077 1869.64644545 1875.62483433 1880.51879882]

[1819.7921786  1823.81151111 1824.45040957 1832.03913417]

[1860.58850039 1863.23148287 1868.57790319 18

Processing series:  74%|███████▍  | 23/31 [3:47:31<1:06:12, 496.52s/it]

[1572.0619355  1575.42317253 1571.33565147 1575.37838574]

(524,)
124
[885.00721642 884.29395935 883.22423583 881.08478879]

[890.71448447 890.40659668 889.94431434 889.01974961]

[876.71310427 875.65318989 874.06369996 870.88472011]

[850.06424715 848.17602248 845.34533245 839.68395247]

[857.15997322 855.52996281 853.08466522 848.19407004]

[848.88152839 847.15120848 844.55597291 839.36550177]

[824.64755699 826.79778931 823.09964651 827.34523144]

[827.59337877 833.79633918 829.23477623 833.70665724]

[848.84599975 848.68752063 850.82627154 848.12861492]

[885.43332302 885.25365082 884.97320594 884.41231354]

[872.44843707 871.81082085 870.85544562 868.94469524]

[905.53329033 911.10073138 905.90784401 911.32476457]

[903.24520816 905.96693278 905.69021097 905.45429652]

[898.06279749 897.68120078 897.10880658 895.96401817]

[855.76943322 854.4793999  852.55429423 848.70408502]

[847.90186509 848.37283818 848.34290865 848.25298971]

[800.22112577 794.85034211 796.31302312 796.614642

Processing series:  77%|███████▋  | 24/31 [3:56:23<59:10, 507.19s/it]  

[639.62134318 639.16819957 636.53635343 634.30295572]

(524,)
124
[1021.53384811 1021.18706476 1024.01856019 1021.24033166]

[1018.66689977 1013.52445202 1014.19639813 1018.18822825]

[1015.0074892  1017.15880757 1014.39754025 1015.40469687]

[1029.56036265 1032.83508592 1033.58239103 1029.79337866]

[1048.45367111 1044.06616888 1046.9143878  1047.9291643 ]

[1053.75112704 1050.56648232 1049.24191537 1053.59127997]

[1046.6942159  1051.5691934  1049.12747319 1047.21460296]

[1048.42084978 1050.14101324 1052.18083297 1048.39600168]

[1053.44305896 1048.52029004 1049.94381826 1053.06655799]

[1043.64345309 1044.68355758 1043.13889908 1048.37863912]

[1032.60591751 1039.45677962 1039.54550166 1037.45593932]

[1046.85837806 1051.20403356 1051.96424633 1052.6555596 ]

[1077.25331545 1071.73783353 1070.84552235 1074.85871341]

[1071.60751103 1076.65289902 1074.07970213 1070.93290524]

[1068.00487817 1074.29472057 1077.02479864 1073.28329672]

[1082.00251043 1075.81718885 1080.46588653 1081.1

Processing series:  81%|████████  | 25/31 [4:09:02<58:17, 582.88s/it]

[880.3773755  885.25606621 887.40658757 887.78676723]

(524,)
124
[1224.35817179 1224.99718671 1229.10332557 1236.08998082]

[1199.91018921 1204.68248943 1207.68745321 1213.83632003]

[1199.80664815 1201.76487245 1205.41798707 1213.1629352 ]

[1205.59750936 1207.10282756 1210.90182106 1217.70361046]

[1204.47951311 1206.37750511 1210.12843873 1217.43952745]

[1219.69533468 1220.15619649 1224.14409185 1232.68266995]

[1223.2936395  1223.31335836 1227.62997045 1235.26591402]

[1219.55833759 1223.43629264 1226.61704949 1234.0228215 ]

[1211.90354378 1216.29710814 1220.44614099 1227.67251142]

[1216.59682181 1220.87870634 1223.99072983 1231.61518301]

[1223.16125173 1225.40670971 1228.70841735 1236.40446182]

[1169.33847152 1177.56453131 1184.00014109 1190.69919806]

[0. 0. 0. 0.]

[1167.2136938  1174.50809522 1177.37770159 1184.82097645]

[1144.53855992 1146.62485375 1149.99202381 1156.72893437]

[1151.25560504 1152.90986111 1155.9307923  1165.21114618]

[1142.25611907 1146.01724603 1149.

Processing series:  84%|████████▍ | 26/31 [4:19:55<50:18, 603.76s/it]

[1008.16772033 1008.5487998  1009.09358852 1010.18299581]

(524,)
124
[3398.38266762 3407.72957306 3418.20517636 3432.99329663]

[3379.97805861 3386.51218393 3396.3572328  3416.047412  ]

[3433.7988523  3440.81759962 3451.26185275 3472.15023207]

[3519.51812148 3533.62879056 3542.94141704 3558.48446402]

[3557.75637892 3564.37247465 3575.50477401 3604.40290786]

[3622.37889677 3630.57200771 3642.6224461  3666.72244875]

[3560.36719065 3568.24242642 3580.23925846 3604.23340155]

[3536.89795831 3544.7552312  3556.6484783  3580.435315  ]

[3560.8923895  3568.74531828 3580.45858187 3603.88490063]

[3544.6987439  3552.43271772 3564.09912863 3587.4321498 ]

[3540.24834466 3547.99605339 3559.64904299 3582.95511806]

[3557.8150959  3573.97559001 3583.55220456 3598.30698454]

[3622.48188082 3630.745217   3642.9255841  3667.28554975]

[3560.55024832 3568.54350478 3580.69840104 3605.00857718]

[3447.58649384 3454.94727364 3466.49550843 3489.59390856]

[3476.65416071 3484.61860428 3496.49891377 35

Processing series:  87%|████████▋ | 27/31 [4:30:11<40:30, 607.60s/it]

[3404.20444043 3402.27896155 3417.39928228 3434.74276703]

(524,)
124
[1495.92538155 1498.92010896 1494.13373153 1484.83737882]

[1514.6941916  1507.56020412 1503.08313233 1494.57666128]

[1503.18314498 1493.82282244 1487.30008479 1478.02352547]

[1444.8997383  1451.79232057 1448.395109   1442.37459803]

[1434.15759392 1439.19564103 1441.8705575  1444.50895339]

[1449.70107412 1439.90869169 1439.73074119 1440.89256187]

[1422.3228196  1425.25164181 1424.10049752 1423.60045009]

[1397.55972058 1409.31214511 1412.81720612 1416.33685316]

[1425.50153254 1419.94234844 1423.65391208 1429.76141282]

[1416.77756605 1413.0263334  1413.41625931 1416.88032177]

[1406.54715559 1418.74127664 1420.06185877 1420.44346634]

[1438.71447903 1436.15133901 1439.47476244 1443.66297272]

[1452.90360371 1442.58725754 1440.32433838 1439.62842092]

[1428.47350127 1436.87841663 1435.28351413 1432.17875611]

[1382.27698012 1390.11875679 1395.84376653 1403.21175971]

[1403.08304884 1399.38568468 1403.91865659 14

Processing series:  90%|█████████ | 28/31 [4:41:14<31:12, 624.23s/it]

[1180.07997596 1177.08057422 1185.0219967  1184.32082652]

(524,)
124
[333.28844643 333.58255165 334.1327721  334.6123214 ]

[354.19962725 354.16008301 354.10077012 353.98215688]

[337.30819244 337.21945785 337.28061137 337.0543961 ]

[340.45349666 340.07381373 339.36913494 338.74390557]

[340.5135499  340.15550559 339.90202562 339.15802336]

[346.60290784 345.71495578 344.27510344 342.70575389]

[348.08717895 347.14736182 346.18332465 344.26294369]

[347.34839544 346.46088255 345.10877353 343.47314109]

[349.78071295 348.75594051 347.5635912  345.50224331]

[348.18944055 347.29456922 346.04906455 344.33574584]

[345.1100048  344.47525028 343.8084154  342.53096606]

[347.86061718 347.00887268 345.71725934 344.13268343]

[351.55013891 350.4618363  349.14831043 346.94874742]

[355.73111822 354.40808463 352.50598858 349.85031257]

[335.1937259  335.58626232 336.62945839 337.00353584]

[325.3821722  327.13631929 329.197295   331.87212796]

[320.41604841 322.68902027 325.38913336 328.961315

Processing series:  94%|█████████▎| 29/31 [4:54:09<22:18, 669.32s/it]

[254.87326721 254.84165405 254.83939912 254.8393587 ]

(524,)
124
[285.00037368 284.77888343 284.76006359 284.75962826]

[282.27194903 282.13772368 282.1247629  282.12440172]

[283.16033706 283.14459386 283.14312887 283.14309018]

[288.87040503 288.98776271 288.99743908 288.99765331]

[294.9456856  295.48651241 295.52332302 295.54920545]

[296.33854714 296.36680551 296.30578004 296.26253868]

[288.96869843 288.8499973  288.84119221 288.84102512]

[287.86778718 287.81700222 287.81328013 287.81321072]

[290.54820847 290.58581977 290.58835377 290.58839556]

[291.90306553 291.93630905 291.93850837 291.93854368]

[289.6817431  289.650033   289.64777258 289.6477321 ]

[297.33825491 297.4809049  297.49284036 297.49311031]

[301.7582371  299.04041079 294.38312301 292.94509071]

[305.0243222  305.09421936 305.0996284  305.09973758]

[296.09643972 295.95773718 295.94899975 295.94886914]

[295.42935444 295.38428239 295.38134139 295.38129511]

[291.95511947 291.87988636 291.87465136 291.87456087]


Processing series:  97%|█████████▋| 30/31 [5:05:33<11:13, 673.94s/it]

[215.59562003 215.55728852 214.38578537 213.54829785]

(524,)
124
[1000.15419324 1004.98079951 1000.94680882 1004.75820169]

[ 998.39842743  999.6054321  1000.14120511 1000.78637792]

[1002.88469432 1002.75760289  998.21259636  999.16619944]

[1027.1268061  1022.63440285 1021.25259543 1020.34727233]

[1032.16186866 1029.54122985 1032.23093068 1028.45329122]

[1039.33752367 1036.99221741 1041.14221544 1038.51680253]

[1017.96232828 1017.32224261 1022.74702836 1020.35858179]

[1012.03778719 1014.68405303 1017.15549699 1017.40094458]

[1039.77537038 1047.11267234 1043.38754472 1047.60594357]

[1043.5168141  1045.6010476  1037.76992434 1042.6612662 ]

[177234.60759725 178123.82662271 179003.22805315 181633.98070691]

[1044.27925747 1039.68180997 1038.16812562 1037.03326208]

[1053.35050191 1049.17364627 1053.26774509 1049.18103929]

[1054.08016691 1051.30141272 1057.45649677 1053.79288185]

[1034.84198534 1035.74420548 1041.48975735 1039.19178968]

[1037.88637106 1041.62008224 1042.9419102

Processing series: 100%|██████████| 31/31 [5:19:17<00:00, 617.97s/it]

[873.4197717  874.76638676 875.29522021 871.99907539]



In [8]:
np.save('data/forecasts_2020.npy', np.array(forecasts_all))

In [69]:
G_lst = []
train_l = 400
total_l = len(Basey)
for i in range(len(h_lst)):
    forecast_mat = forecasts_all[:,:,i] # (num of series, num of forecasts), (31, 123)
    # print(forecast_mat.shape)

    Y_mat = np.array(S @ np.array(Basey).T) # (num of series, num of dates)

    h = h_lst[i] # [1, 3, 6, 12]
    forecast_range = np.array(range(h+train_l-1, total_l-1)) 
    # print(num_of_forecasts)
    num_of_forecasts = len(forecast_range)

    # calculate residuals
    residuals_mat = forecast_mat[:, 0:num_of_forecasts] - Y_mat[:, forecast_range] # (num of series, num of forecasts)
    # print(residuals_mat.shape)

    G_h = G_mat(S, forecast_mat, residuals_mat) # (num of base stock, num of series)
    G_lst.append(G_h)

G_lst = np.array(G_lst)
print(G_lst.shape)
np.save('data/G_lst.npy', G_lst)



(31, 31)
S.T shape: (30, 31)
W_inverse shape: (31, 31)
S shape: (31, 30)
Data type of S: <class 'numpy.ndarray'>
Data type of W_inverse: <class 'numpy.ndarray'>
(31, 31)
S.T shape: (30, 31)
W_inverse shape: (31, 31)
S shape: (31, 30)
Data type of S: <class 'numpy.ndarray'>
Data type of W_inverse: <class 'numpy.ndarray'>
(31, 31)
S.T shape: (30, 31)
W_inverse shape: (31, 31)
S shape: (31, 30)
Data type of S: <class 'numpy.ndarray'>
Data type of W_inverse: <class 'numpy.ndarray'>
(31, 31)
S.T shape: (30, 31)
W_inverse shape: (31, 31)
S shape: (31, 30)
Data type of S: <class 'numpy.ndarray'>
Data type of W_inverse: <class 'numpy.ndarray'>
(4, 30, 31)
